### ISSUE TITLE
The service is stopped !!!

### ISSUE THREAD

**Issue by Suleman-Elahi** [mistressofjellyfish/softwarelimiter#1]
The SoftwareLimiter service stops and doesn't start. When I am trying to start it manually it throws the following error.

"Error 1053: The service did not respond to the start or control request in a timely fashion"

I am using Windows 10  Build: 150663.632

**Comment by hackathi** [comment]
Which version do you run? Try to compile from source and re-install the service.

**Comment by Suleman-Elahi** [comment]
In the latest version of the Software Limiter.

Well, okay I will try to compile it from the source and will let you know.
